name: Haskell Stack CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Setup Haskell Stack
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.2.7'
        stack-version: '2.9.3'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}

    - name: Install dependencies
      run: stack --no-terminal setup

    - name: Build
      run: stack --no-terminal build --fast

    - name: Test
      run: stack --no-terminal test
